isehan/urls.py
from django.conf.urls import url
from django.urls import path
from isehan import views
from django.contrib.auth import views as django_auth_views

app_name = 'isehan'

urlpatterns = [
    path('', views.TopPage.as_view(), name='top'),
    path('base/', views.BasePage.as_view(), name='base'),
    path('items/', views.ItemList.as_view(), name='item_list'),
    path('items/<int:pk>', views.ItemDetail.as_view(), name='item_detail'),
    path('parent_category/<int:pk>', views.ParentCategoryView.as_view(), name='parent_category_view'),
    path('category/<int:pk>', views.CategoryView.as_view(), name='category_view'),
    path('login', views.Login.as_view(), name="login"),
    path('logout', django_auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('signup_done/<token>', views.SignUpDone.as_view(), name='signup_done'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name="user_detail"),
    path("user/<int:pk>/update/", views.UserUpdateView.as_view(), name="user_update"),
    path('cart/<int:pk>', views.ShoppingCartDetail.as_view(), name='cart'),
    path('ajax_amount/', views.update_cart_item_amount, name='update_cart_item_amount'),
    path('ajax_delete/', views.delete_cart_item, name='delete_cart_item'),
]

mk_ec/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('isehan.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

isehan/models.py
from django.db import models
from django import forms
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.db.models import F, Sum


# Create your models here.
class ParentCategory(models.Model):
    class Meta:
        verbose_name = '親カテゴリー'
        verbose_name_plural = '親カテゴリー'

    name = models.CharField(
        verbose_name = '名前',
        max_length = 150,
        default = '',
        null = True,
        blank = True,
    )
    def __str__(self):
        return self.name

class Category(models.Model):
    class Meta:
        verbose_name = '子カテゴリー'
        verbose_name_plural = '子カテゴリー'

    name = models.CharField(
        verbose_name = '名前',
        max_length = 150,
        default = '',
        null = True,
        blank = True,
    )
    parent = models.ForeignKey(
        ParentCategory,
        verbose_name='親カテゴリー',
        related_name='parent_category',
        on_delete=models.CASCADE,
        null = True,
        blank = True,
    )
    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = '商品'
        verbose_name_plural = '商品'

    thumbnail = models.ImageField(
        verbose_name = 'サムネイル',
        upload_to = 'thumbnails/',
        null = True,
        blank = True,
    )
    image = models.ImageField(
        verbose_name = '商品画像',
        upload_to = 'images/',
        null = True,
        blank = True,
    )
    name = models.CharField(
        verbose_name = '名前',
        max_length = 150,
        null = True,
        blank = True,
    )

    price = models.IntegerField(
        verbose_name = '価格',
        null = True,
        blank = True,
    )

    description1 = models.TextField(
        verbose_name = '説明',
        null = True,
        blank = True,
    )

    p_category = models.ForeignKey(
        ParentCategory,
        verbose_name = '親カテゴリー',
        related_name = 'p_category',
        on_delete = models.CASCADE,
        null = True,
        blank = True,
    )
    category1 = models.ForeignKey(
        Category,
        verbose_name='カテゴリー1',
        related_name='category1',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )



class MyUserManager(BaseUserManager):
    """ユーザーマネージャー."""
    use_in_migrations = True
    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = 'ユーザ'
        verbose_name_plural = 'ユーザ'

    """カスタムユーザーモデル."""
    email = models.EmailField('メールアドレス', max_length=150, null=False, blank=False, unique=True)
    # name = models.CharField('名前', max_length=150, null=False, blank=False)
    zipcode = models.CharField('郵便番号', max_length = 8, blank=True)
    address1 = models.CharField('都道府県', max_length=500, null=True, blank=True)
    address2 = models.CharField('市区町村番地', max_length=500, null=True, blank=True)
    address3 = models.CharField('建物名', max_length=500, null=True, blank=True)

    is_staff = models.BooleanField(
        '管理者',
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        '有効',
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = MyUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['zipcode', 'address1', 'address2', 'address3']
    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email


class ShoppingCart(models.Model):
    user = models.OneToOneField(
        User,
        verbose_name = 'ユーザ',
        related_name = 'cart',
        on_delete = models.CASCADE
    )
    @property
    def item_count(self):
        return self.cart_items.all().aggregate(amount = Sum('amount'))['amount']
    @property
    def total_price(self):
        return self.cart_items.all().aggregate(total=Sum(F('product__price') * F('amount')))['total']

class ShoppingCartItem(models.Model):
    cart = models.ForeignKey(
        ShoppingCart,
        related_name = 'cart_items',
        verbose_name = 'ショッピングカート',
        on_delete = models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        verbose_name = '商品',
        on_delete = models.CASCADE
    )
    amount = models.IntegerField(
        verbose_name = '数量'
    )

isehan/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import *
from django.core.exceptions import ValidationError

class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'zipcode', 'address1', 'address2', 'address3')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            if field.label == '郵便番号':
                field.widget.attrs['placeholder'] = field.label + ' (8890014)'
                continue
            field.widget.attrs['placeholder'] = field.label

    # 本登録に失敗してactivateされてないアドレスを再登録できるようにDBから削除
    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'zipcode', 'address1', 'address2', 'address3')

isehan/views.py
from django.views.generic import *
# from .models import *
from django.contrib.auth.views import LoginView
from .forms import *
from django.shortcuts import render, redirect, resolve_url
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from django.core.signing import BadSignature, SignatureExpired, dumps, loads
from django.urls import reverse
from .forms import UserForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import get_template
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import OnlyYouMixin, CartMixin
from django.db.models import Q



# Create your views here.
class TopPage(TemplateView):
    model = Product
    template_name = 'isehan/top.html'

    def get_context_data(self, **kwargs):
        context = super(TopPage, self).get_context_data(**kwargs)
        products = Product.objects.all()
        context['all_items'] = products
        random_items = Product.objects.order_by('?')[:4]
        context['random_items'] = random_items
        context
        return context

class BasePage(TemplateView):
    template_name = 'isehan/base.html'


class ItemList(ListView):
    model = Product
    template_name = 'isehan/item_list.html'

    def get_queryset(self):
        products = Product.objects.all()
        if 'query' in self.request.GET and self.request.GET['query'] != None:
            query = self.request.GET['query']
            products = products.filter(name__icontains=query)
        return products


class ItemDetail(DetailView):
    model = Product
    template_name = 'isehan/item_detail.html'


class ParentCategoryView(TemplateView):
    template_name = 'isehan/category_list.html'

    def get_context_data(self, **kwargs):
        context = super(ParentCategoryView, self).get_context_data(**kwargs)
        category_id = self.kwargs['pk']
        category_items = Product.objects.filter(p_category=category_id)
        context['category_items'] = category_items
        context['category_name'] = ParentCategory.objects.filter(id=category_id)
        return context

class CategoryView(TemplateView):
    template_name = 'isehan/category_list.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        category_id = self.kwargs['pk']
        category_items = Product.objects.filter(
            Q(category1=category_id)
        )
        context['category_items'] = category_items
        context['category_name'] = Category.objects.filter(id=category_id)
        return context



class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'isehan/login.html'

class SignUp(CreateView):
    """ユーザー仮登録"""
    template_name = 'isehan/signup.html'
    form_class = SignUpForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('isehan/mail_template/signup/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('isehan/mail_template/signup/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        messages.success(self.request, '本登録用リンクを送付しました')
        return HttpResponseRedirect(reverse('isehan:signup'))

class SignUpDone(TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'isehan/signup_done.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()

                    his_cart = ShoppingCart()
                    his_cart.user = user
                    his_cart.save()

                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

class UserDetailView(OnlyYouMixin, DetailView):
    model = User
    template_name = 'isehan/user_detail.html'

class UserUpdateView(OnlyYouMixin, UpdateView):
    model = User
    template_name = 'isehan/user_update.html'
    form_class = UserForm

    def get_success_url(self):
        return resolve_url('isehan: user_detail', pk=self.kwargs['pk'])


class ShoppingCartDetail(CartMixin, DetailView):
    model = ShoppingCart
    template_name = "isehan/shopping_cart.html"

    def post(self, request, *args, **kwargs):
        user = request.user
        product_pk = request.POST.get('product_pk')
        product = Product.objects.get(pk=product_pk)
        amount = request.POST.get('amount')

        exist = ShoppingCartItem.objects.filter(cart__user=user).filter(product=product)

        # すでにカートに存在する商品の場合は個数をインクリメント
        if len(exist) > 0:
            current_amount = exist[0].amount
            exist[0].amount = current_amount + int(amount)
            exist[0].save()
        else:
            new_cart_item = ShoppingCartItem()
            new_cart_item.cart = request.user.cart
            new_cart_item.product = product
            new_cart_item.amount = int(amount)
            new_cart_item.save()
        return HttpResponseRedirect(reverse('isehan:cart', kwargs={'pk': self.get_object().pk}))

def update_cart_item_amount(request):
    cart_item_pk = request.POST.get('cart_item_pk')
    new_amount = request.POST.get('amount')

    if cart_item_pk == None or new_amount == None:
        return JsonResponse({'error': 'invalid parameter'})
    if int(new_amount) <= 0:
        return JsonResponse({'error': 'amount must be greater than zero'})

    try:
        cart_item = ShoppingCartItem.objects.get(pk=cart_item_pk)
        cart_item.amount = int(new_amount)
        cart_item.save()
        print(cart_item.amount)
        return JsonResponse({'success': True})
    except Exception as e:
        return JsonResponse({'error': str(e.args)})

def delete_cart_item(request):
    cart_item_pk = request.POST.get('cart_item_pk')
    if cart_item_pk == None:
        return JsonResponse({'error': 'invalid parameter'})
    try:
        cart_item = ShoppingCartItem.objects.get(pk=cart_item_pk)
        cart_item.delete()
        return JsonResponse({'success': True})
    except Exception as e:
        return JsonResponse({'error': str(e.args)})

templates/isehan/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--jQuery CDN-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <!--Bootstrap CDN-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"-->
          <!--integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">

    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)"/>


    <title>isehan</title>
</head>
<body>
<header class="section-header">
    <section class="header-above">
        <div class="container">
        <div class="col-lg-12 col-sm-12">
            <div class="widgets-wrap d-flex justify-content-end">
                {% if user.is_authenticated and not user.is_superuser %}
                <div class="widget-header icontext">
                    <a href="{% url 'isehan:cart' user.cart.pk %}" class="icontext">
                        <div class="icon-wrap icon-sm bg2 round text-secondary"><i
                                class="fa fa-shopping-cart"></i></div>
                        <div class="text-wrap">
                            <small>カート</small>
                            <span>{{ user.cart.item_count|default_if_none:"0" }}商品</span>
                        </div>
                    </a>
                </div>
                {% endif %}
                <div class="widget-header icontext">
                    <div class="icon-wrap icon-sm bg2 round text-secondary"><i class="fa fa-user"></i></div>
                    <div class="text-wrap">
                        {% if user.is_authenticated %}
                        <small>{{ user.email }}さん</small>
                        <span><a href="{% url 'isehan:logout' %}">Logout</a></span>
                        {% else %}
                        <small>ゲスト</small>
                        <span><a href="{% url 'isehan:login' %}">Login</a></span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
    <section class="header-main">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-10">
                    <ul class="nav nav-pills">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'isehan:top' %}">
                                <div class="brand-wrap">
                                    <i class="fas fa-home"></i>
                                </div>
                            </a>
                        </li>
                        {% for p_category in all_parent_category %}
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="{% url 'isehan:parent_category_view' p_category.pk %}">{{ p_category }}</a>
                            <div class="dropdown-menu">
                                {% for category in other_category %}
                                {% if category.parent.pk == p_category.pk %}
                                <a class="dropdown-item" href="{% url 'isehan:category_view' category.pk %}">{{ category }}</a>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div> <!-- col.// -->
                <div class="col-md-2 col-sm-2">
                    <form method="get" action="{% url 'isehan:item_list' %}" class="search-wrap">
                        <div class="input-group">
                            <input name="query" type="text" class="form-control" placeholder="Search">
                            <div class="input-group-append">
                                <button id="id_search_button" class="btn btn-warning" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

</header>
<div class="container" style="padding: 2rem">
    {% block content %}{% endblock %}
</div>
<footer class="section-footer bg2">
    <div class="container">
        <section class="footer-bottom row">

            <div class="col-sm-12">
                <p class="text-sm-right">
                    Copyright © 2020
                </p>
            </div>
        </section>
    </div>
</footer>

<script type="text/javascript">
    function getCookie(name) {
       var cookieValue = null;
       if (document.cookie && document.cookie !== '') {
           var cookies = document.cookie.split(';');
           for (var i = 0; i < cookies.length; i++) {
               var cookie = jQuery.trim(cookies[i]);
               // Does this cookie string begin with the name we want?
               if (cookie.substring(0, name.length + 1) === (name + '=')) {
                   cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                   break;
               }
           }
       }
       return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
       // these HTTP methods do not require CSRF protection
       return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
       beforeSend: function (xhr, settings) {
           if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
               xhr.setRequestHeader("X-CSRFToken", csrftoken);
           }
       }
    });






</script>

{% block scripts %}{% endblock %}

</body>
</html>

templates/isehan/category_list.html
{% extends "isehan/base.html" %}
{% block content %}
{% load static %}

{% for name in category_name %}
{% if forloop.first %}
<h2>「{{ name.name }}」の商品一覧</h2>
{% endif %}
{% endfor %}

<div class="row-sm">
    {% for item in category_items %}
    <div class="col-md-3">
        <figure class="card card-product">
            <div class="img-wrap">
                <a href="{% url 'isehan:item_detail' item.pk %}">
                    <img src="{{ item.thumbnail.url }}">
                </a>
            </div>
            <figcaption class="info-wrap">
                <h4 class="title "><a href="{% url 'isehan:item_detail' item.pk %}">{{ item.name }}</a></h4>
                <div class="price-wrap">
                    <span class="price-new">{{ item.price }}円</span><br>
                </div>
            </figcaption>
        </figure>
    </div>
    {% endfor %}

</div>
{% endblock %}

templates/isehan/item_list.html
{% extends "isehan/base.html" %}
{% block content %}
{% load static %}
    <div class="row-sm">
    {% for object in object_list %}

        <div class="col-md-3">
            <figure class="card card-product">
                <div class="img-wrap">
                    <a href="{% url 'isehan:item_detail' object.pk %}">
                        <img src="{{ object.thumbnail.url }}">
                    </a>
                </div>
                <figcaption class="info-wrap">
                    <h6 class="title "><a href="{% url 'isehan:item_detail' object.pk %}">{{ object.name }}</a></h6>
                    <div class="price-wrap">
                        <span class="price-new">{{ object.price }}円</span><br>
                    </div>
                </figcaption>
            </figure>
        </div>

    {% endfor %}
    </div>
{% endblock %}

templates/isehan/shopping_cart.html
{% extends "isehan/base.html" %}
{% block content %}
{% load static %}

{% if object.cart_items.all %}
<div class="card shopping-cart">
    <div class="card-body">
        {% for cart_item in object.cart_items.all %}
        <div class="row">
            <div class="col-12 col-sm-12 col-md-2 text-center">
                <img class="img-responsive" src="{{ cart_item.product.thumbnail.url }}" alt="prewiew" width="120"
                     height="80">
            </div>
            <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                <h4 class="product-name"><strong>{{ cart_item.product.name }}</strong></h4>
                <h4>
                    <small>{{ cart_item.product.description }}</small>
                </h4>
            </div> <!-- col -->
            <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                    <h6><strong>{{ cart_item.product.price }} <span class="text-muted">x</span></strong></h6>
                </div>
                <div class="col-4 col-sm-4 col-md-4">
                    <div class="quantity">
                        <input name="amount" pk="{{ cart_item.pk }}" type="number" class="form-control" step="1"
                               max="99" min="1" title="Qty" class="qty" size="4" value="{{ cart_item.amount }}">
                    </div>
                </div>
                <div class="col-2 col-sm-2 col-md-2 text-right">
                    <button name="delete" pk="{{ cart_item.pk }}" type="button" class="btn btn-outline-danger btn-xs">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                </div>
            </div> <!-- col -->
        </div> <!-- row -->
        <hr>
        {% endfor %}
    </div> <!-- card body -->
    <div class="card-footer">
        <a href="" class="btn btn-success pull-right">Checkout</a>
        <div class="float-right">Total price: <b> ¥{{ object.total_price }}</b></div>
    </div>
    </div> <!-- card footer -->
</div> <!-- card -->
{% else %}
<div class="card shopping-cart">
    <p>カートが空です</p>
</div>
{% endif %}
{% endblock %}

{% block scripts %}
<script>
    function call_update_amount(_pk, _amount) {
        return $.ajax({
            url: '{% url "isehan:update_cart_item_amount" %}',
            type: 'POST',
            dataType: 'json',
            data: {
                cart_item_pk: _pk,
                amount: _amount
            }
        });
    }
    function call_delete_item(_pk) {
        return $.ajax({
            url: '{% url "isehan:delete_cart_item" %}',
            type: 'POST',
            dataType: 'json',
            data: {
                cart_item_pk: _pk
            }
        });
    }

    $(function() {
        var $input_amount = $('input[name="amount"]');
        var $delete_button = $('button[name="delete"]');
        $input_amount.on('change', function() {
            var cart_item_pk = $(this).attr('pk');
            var new_amount = parseInt($(this).val());
            call_update_amount(cart_item_pk, new_amount)
            .done((data) => {
                if (data.success) {
                    location.reload();
                    return;
                }
                alert(data.error);
            })
            .fail((ata, textStatus, xhr) => {
                alert(xhr);
            });
        });
        $delete_button.on('click', function() {
            var cart_item_pk = $(this).attr('pk');
            call_delete_item(cart_item_pk)
            .done((data) => {
                if (data.success) {
                    location.reload();
                    return;
                }
                alert(data.error);
            })
            .fail((ata, textStatus, xhr) => {
                alert(xhr);
            });
        });
    })
</script>
{% endblock %}

templates/isehan/signup_done.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" ></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <title>title here</title>

</head>
<body>
        <div class="jumbotron text-xs-center">
            <h1 class="display-3">Thank You!</h1>
                <p class="lead"><strong>Enjoy shopping!</strong> </p>
            <hr>
            <a class="btn btn-success" href="{% url 'isehan:login' %}">login</a>
        </div>

</body>
</html>